export const UI_TEXT = {
  title: 'الخطوة 2: معلومات الحساب',
  name: 'الاسم',
  address: 'العنوان',
  descriptionRegistered: 'مرحبا بك مرة أخرى! سيتم استخدام بياناتك الحالية.',
  descriptionUnregistered:
    'يرجى تعبئة المعلومات التالية لإكمال تسجيلك. بياناتك ستكون آمنة وستسهل استخدامك في المستقبل.',
  phoneLabel: 'رقم الهاتف:',
  namePlaceholder: 'الاسم الكامل',
  addressPlaceholder: 'العنوان',
  fetchLocationButton: 'جلب الإحداثيات الحالية',
  latitudeLabel: 'خط العرض:',
  longitudeLabel: 'خط الطول:',
  backButton: 'السابق',
  nextButton: 'إتمام',
  otpDialogTitle: 'تأكيد رقم الجوال',
  otpDialogMessage: (phone: string) => `تم إرسال كود تأكيد إلى ${phone}`,
  otpInputPlaceholder: 'ادخل كود التأكيد',
  confirmButton: 'تأكيد',
  cancelButton: 'إلغاء',
  termsAgreement: 'أوافق على الشروط والأحكام',
  termsLink: 'الشروط والأحكام',
  loadingButton: 'جاري إرسال الطلب...',
};
